modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="ars_wa" 
    version="1.0.0"
    displayName="Weapon Awakening"
    authors="Robbie"
    description='''
    Un addon para Ars Nouveau que permite despertar el poder oculto de las armas.
    '''

[[dependencies.ars_wa]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ars_wa]]
    modId="ars_nouveau"
    mandatory=true
    versionRange="[4.12.7,)"
    ordering="AFTER"
    side="BOTH"
